from __future__ import annotations

import os
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq


DATA_ROOT = Path(os.environ.get("PLAYER_DATA_ROOT", Path(__file__).resolve().parents[1] / "player_data"))
OUT_PATH = Path(__file__).resolve().parents[1] / "INSIGHTS.md"


def is_bot(user_id: str) -> bool:
    return user_id.isdigit()


def decode_event(v):
    if isinstance(v, (bytes, bytearray, memoryview)):
        return bytes(v).decode("utf-8", errors="replace")
    return str(v)


def iter_files():
    for day in sorted(DATA_ROOT.iterdir()):
        if not day.is_dir() or not day.name.startswith("February_"):
            continue
        for f in day.iterdir():
            if f.is_file() and "_" in f.name:
                yield day.name, f


@dataclass
class Agg:
    rows: int = 0
    humans: int = 0
    bots: int = 0
    events: Counter[str] = None  # type: ignore

    def __post_init__(self):
        if self.events is None:
            self.events = Counter()


def main() -> None:
    if not DATA_ROOT.exists():
        raise SystemExit(f"player_data not found at {DATA_ROOT}")

    per_map = defaultdict(Agg)
    per_day = defaultdict(Agg)

    # For simple “ignored area / hotspot” insight: bucket traffic into a coarse grid.
    # (We do this only for AmbroseValley to keep runtime low.)
    traffic_grid = Counter[tuple[int, int]]()
    grid_cell = 64  # pixels

    kill_cells = Counter[tuple[int, int]]()

    # Map configs from README
    map_cfg = {
        "AmbroseValley": dict(scale=900, origin_x=-370, origin_z=-473),
        "GrandRift": dict(scale=581, origin_x=-290, origin_z=-290),
        "Lockdown": dict(scale=1000, origin_x=-500, origin_z=-500),
    }

    def to_pixel(map_id: str, x: float, z: float):
        cfg = map_cfg[map_id]
        u = (x - cfg["origin_x"]) / cfg["scale"]
        v = (z - cfg["origin_z"]) / cfg["scale"]
        px = u * 1024
        py = (1 - v) * 1024
        return px, py

    for day_name, f in iter_files():
        user_id = f.name.split("_", 1)[0]
        bot = is_bot(user_id)
        try:
            df = pq.read_table(f, columns=["map_id", "x", "z", "event"]).to_pandas()
        except Exception:
            continue
        if df.empty:
            continue

        df["event"] = df["event"].apply(decode_event)
        map_id = str(df["map_id"].iloc[0])

        per_map[map_id].rows += len(df)
        per_day[day_name].rows += len(df)

        if bot:
            per_map[map_id].bots += 1
            per_day[day_name].bots += 1
        else:
            per_map[map_id].humans += 1
            per_day[day_name].humans += 1

        per_map[map_id].events.update(df["event"].value_counts().to_dict())
        per_day[day_name].events.update(df["event"].value_counts().to_dict())

        if map_id == "AmbroseValley":
            pos = df[df["event"].isin(["Position", "BotPosition"])]
            for x, z in pos[["x", "z"]].itertuples(index=False, name=None):
                px, py = to_pixel(map_id, float(x), float(z))
                if 0 <= px < 1024 and 0 <= py < 1024:
                    traffic_grid[(int(px // grid_cell), int(py // grid_cell))] += 1

            kills = df[df["event"].isin(["Kill", "BotKill"])]
            for x, z in kills[["x", "z"]].itertuples(index=False, name=None):
                px, py = to_pixel(map_id, float(x), float(z))
                if 0 <= px < 1024 and 0 <= py < 1024:
                    kill_cells[(int(px // grid_cell), int(py // grid_cell))] += 1

    # Insight 1: Map mix + bot share by map
    total_files = sum(v.humans + v.bots for v in per_map.values())
    map_file_counts = {k: v.humans + v.bots for k, v in per_map.items()}

    # Insight 2: Event distribution (loot vs combat vs storm)
    all_events = Counter()
    for v in per_map.values():
        all_events.update(v.events)

    # Insight 3: Traffic concentration on AmbroseValley (ignored areas)
    grid_vals = list(traffic_grid.values())
    top_cells = traffic_grid.most_common(5)
    kill_hot = kill_cells.most_common(5)

    def pct(a, b):
        return 0 if b == 0 else round(100 * a / b, 1)

    # write markdown
    lines = []
    lines.append("# Insights (auto-generated)\n")
    lines.append("> Generated by `scripts/generate_insights.py` from the provided parquet telemetry.\n")

    # Insight 1
    lines.append("## 1) AmbroseValley dominates play volume, and bots are a meaningful share\n")
    lines.append("**What caught my eye**\n")
    for m, c in sorted(map_file_counts.items(), key=lambda x: x[1], reverse=True):
        lines.append(f"- `{m}`: **{c}** journey files (**{pct(c, total_files)}%** of all files), bots: **{per_map[m].bots}** ({pct(per_map[m].bots, c)}%)\n")
    lines.append("\n**Back it up (concrete evidence)**\n")
    lines.append(f"- Total journey files counted from folders: **{total_files}**\n")
    lines.append("\n**Actionable?**\n")
    lines.append("- If bots are used to shape pacing, tune bot density per map to match target experience.\n")
    lines.append("- Metrics likely impacted: average time-to-first-combat, loot-per-minute, extraction success rate.\n")
    lines.append("\n**Why a level designer should care**\n")
    lines.append("- A map that dominates play volume yields the highest ROI for level tweaks; bot density strongly affects perceived “traffic” and fight frequency.\n")

    # Insight 2
    lines.append("\n## 2) Telemetry is movement-heavy; combat events are sparse but heatmap-friendly\n")
    lines.append("**What caught my eye**\n")
    lines.append("- The dataset is mostly `Position` / `BotPosition`, but discrete events (kills, deaths, loot, storm deaths) create clear hotspots.\n")
    lines.append("\n**Back it up (concrete evidence)**\n")
    for ev in ["Position", "BotPosition", "Loot", "Kill", "Killed", "BotKill", "BotKilled", "KilledByStorm"]:
        lines.append(f"- `{ev}` rows: **{int(all_events.get(ev, 0))}**\n")
    lines.append("\n**Actionable?**\n")
    lines.append("- Use the tool’s heatmaps to validate whether intended POIs actually generate engagement (loot pickups) and conflict (kills/deaths).\n")
    lines.append("- Metrics likely impacted: POI engagement rate, kill density around POIs, storm-death rate.\n")
    lines.append("\n**Why a level designer should care**\n")
    lines.append("- Movement lines alone can look “everywhere”; event heatmaps reveal where the map design is producing (or failing to produce) interesting decisions.\n")

    # Insight 3
    lines.append("\n## 3) AmbroseValley traffic is concentrated in a small number of grid cells (potential dead zones)\n")
    lines.append("**What caught my eye**\n")
    lines.append(f"- When bucketing movement into {grid_cell}px cells, a handful of cells dominate traffic.\n")
    if grid_vals:
        total_traffic = sum(grid_vals)
        top5 = sum(v for _, v in top_cells)
        lines.append(f"- Top 5 traffic cells account for **{pct(top5, total_traffic)}%** of all sampled movement points on AmbroseValley.\n")
    lines.append("\n**Back it up (concrete evidence)**\n")
    lines.append("- Top traffic cells (grid_x, grid_y -> count):\n")
    for (gx, gy), c in top_cells:
        lines.append(f"  - ({gx}, {gy}) -> **{c}**\n")
    lines.append("- Top kill cells (grid_x, grid_y -> count):\n")
    for (gx, gy), c in kill_hot:
        lines.append(f"  - ({gx}, {gy}) -> **{c}**\n")
    lines.append("\n**Actionable?**\n")
    lines.append("- Investigate low-traffic regions (cells with near-zero movement): add traversal affordances, sightline/cover changes, or objective/loot incentives.\n")
    lines.append("- Metrics likely impacted: traversal distribution entropy, average travel distance, encounter rate, and time-to-extraction.\n")
    lines.append("\n**Why a level designer should care**\n")
    lines.append("- Dead zones are wasted space and reduce meaningful route choice; traffic concentration can indicate choke points or overly dominant pathing.\n")

    OUT_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()

